// Code generated by gobok v1.0.0. DO NOT EDIT.

package bookingdate

import (
	"github.com/iondodon/go-vbs/repository"
)

func NewBookingDateRepository(queries *repository.Queries) bookingDateRepository {
	return bookingDateRepository{
		queries: queries,
	}
}
