// Code generated by gobok v1.0.0. DO NOT EDIT.

package bookingdate

import (
	"github.com/iondodon/go-vbs/repository"
)

type BookingDateRepositoryBuilder struct {
	instance *BookingDateRepository
}

func NewBookingDateRepositoryBuilder() *BookingDateRepositoryBuilder {
	return &BookingDateRepositoryBuilder{
		instance: &BookingDateRepository{},
	}
}

func (b *BookingDateRepositoryBuilder) Queries(v *repository.Queries) *BookingDateRepositoryBuilder {
	b.instance.queries = v
	return b
}

func (b *BookingDateRepositoryBuilder) Build() *BookingDateRepository {
	return b.instance
}
