// Code generated by gobok v1.0.0. DO NOT EDIT.

package booking

import (
	"github.com/iondodon/go-vbs/repository"
)

type BookingRepositoryBuilder struct {
	instance *BookingRepository
}

func NewBookingRepositoryBuilder() *BookingRepositoryBuilder {
	return &BookingRepositoryBuilder{
		instance: &BookingRepository{},
	}
}

func (b *BookingRepositoryBuilder) Queries(v *repository.Queries) *BookingRepositoryBuilder {
	b.instance.queries = v
	return b
}

func (b *BookingRepositoryBuilder) Build() *BookingRepository {
	return b.instance
}
