// Code generated by gobok v1.0.0. DO NOT EDIT.

package booking

import (
	"github.com/iondodon/go-vbs/repository"
)

func NewBookingRepository(queries *repository.Queries) bookingRepository {
	return bookingRepository{
		queries: queries,
	}
}
