// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/iondodon/go-vbs/customer/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// FindByUUID provides a mock function with given fields: ctx, cUUID
func (_m *MockCustomerRepository) FindByUUID(ctx context.Context, cUUID uuid.UUID) (*domain.Customer, error) {
	ret := _m.Called(ctx, cUUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUUID")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Customer, error)); ok {
		return rf(ctx, cUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Customer); ok {
		r0 = rf(ctx, cUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, cUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomerRepository_FindByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUUID'
type MockCustomerRepository_FindByUUID_Call struct {
	*mock.Call
}

// FindByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - cUUID uuid.UUID
func (_e *MockCustomerRepository_Expecter) FindByUUID(ctx interface{}, cUUID interface{}) *MockCustomerRepository_FindByUUID_Call {
	return &MockCustomerRepository_FindByUUID_Call{Call: _e.mock.On("FindByUUID", ctx, cUUID)}
}

func (_c *MockCustomerRepository_FindByUUID_Call) Run(run func(ctx context.Context, cUUID uuid.UUID)) *MockCustomerRepository_FindByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCustomerRepository_FindByUUID_Call) Return(_a0 *domain.Customer, _a1 error) *MockCustomerRepository_FindByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomerRepository_FindByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Customer, error)) *MockCustomerRepository_FindByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
