// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/iondodon/go-vbs/booking/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGetAllBookingsUseCase is an autogenerated mock type for the GetAllBookingsUseCase type
type MockGetAllBookingsUseCase struct {
	mock.Mock
}

type MockGetAllBookingsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetAllBookingsUseCase) EXPECT() *MockGetAllBookingsUseCase_Expecter {
	return &MockGetAllBookingsUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockGetAllBookingsUseCase) Execute(ctx context.Context) ([]domain.Booking, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Booking, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Booking); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetAllBookingsUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetAllBookingsUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGetAllBookingsUseCase_Expecter) Execute(ctx interface{}) *MockGetAllBookingsUseCase_Execute_Call {
	return &MockGetAllBookingsUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockGetAllBookingsUseCase_Execute_Call) Run(run func(ctx context.Context)) *MockGetAllBookingsUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGetAllBookingsUseCase_Execute_Call) Return(_a0 []domain.Booking, _a1 error) *MockGetAllBookingsUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetAllBookingsUseCase_Execute_Call) RunAndReturn(run func(context.Context) ([]domain.Booking, error)) *MockGetAllBookingsUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetAllBookingsUseCase creates a new instance of MockGetAllBookingsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetAllBookingsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetAllBookingsUseCase {
	mock := &MockGetAllBookingsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
