// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	controller "github.com/iondodon/go-vbs/booking/controller"
	domain "github.com/iondodon/go-vbs/vehicle/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVehicleRepository is an autogenerated mock type for the VehicleRepository type
type MockVehicleRepository struct {
	mock.Mock
}

type MockVehicleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVehicleRepository) EXPECT() *MockVehicleRepository_Expecter {
	return &MockVehicleRepository_Expecter{mock: &_m.Mock}
}

// FindByUUID provides a mock function with given fields: ctx, vUUID
func (_m *MockVehicleRepository) FindByUUID(ctx context.Context, vUUID uuid.UUID) (*domain.Vehicle, error) {
	ret := _m.Called(ctx, vUUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUUID")
	}

	var r0 *domain.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Vehicle, error)); ok {
		return rf(ctx, vUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Vehicle); ok {
		r0 = rf(ctx, vUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, vUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVehicleRepository_FindByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUUID'
type MockVehicleRepository_FindByUUID_Call struct {
	*mock.Call
}

// FindByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - vUUID uuid.UUID
func (_e *MockVehicleRepository_Expecter) FindByUUID(ctx interface{}, vUUID interface{}) *MockVehicleRepository_FindByUUID_Call {
	return &MockVehicleRepository_FindByUUID_Call{Call: _e.mock.On("FindByUUID", ctx, vUUID)}
}

func (_c *MockVehicleRepository_FindByUUID_Call) Run(run func(ctx context.Context, vUUID uuid.UUID)) *MockVehicleRepository_FindByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVehicleRepository_FindByUUID_Call) Return(_a0 *domain.Vehicle, _a1 error) *MockVehicleRepository_FindByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVehicleRepository_FindByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Vehicle, error)) *MockVehicleRepository_FindByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// VehicleHasBookedDatesOnPeriod provides a mock function with given fields: ctx, vUUID, period
func (_m *MockVehicleRepository) VehicleHasBookedDatesOnPeriod(ctx context.Context, vUUID uuid.UUID, period controller.DatePeriodDTO) (bool, error) {
	ret := _m.Called(ctx, vUUID, period)

	if len(ret) == 0 {
		panic("no return value specified for VehicleHasBookedDatesOnPeriod")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, controller.DatePeriodDTO) (bool, error)); ok {
		return rf(ctx, vUUID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, controller.DatePeriodDTO) bool); ok {
		r0 = rf(ctx, vUUID, period)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, controller.DatePeriodDTO) error); ok {
		r1 = rf(ctx, vUUID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VehicleHasBookedDatesOnPeriod'
type MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call struct {
	*mock.Call
}

// VehicleHasBookedDatesOnPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - vUUID uuid.UUID
//   - period controller.DatePeriodDTO
func (_e *MockVehicleRepository_Expecter) VehicleHasBookedDatesOnPeriod(ctx interface{}, vUUID interface{}, period interface{}) *MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call {
	return &MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call{Call: _e.mock.On("VehicleHasBookedDatesOnPeriod", ctx, vUUID, period)}
}

func (_c *MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call) Run(run func(ctx context.Context, vUUID uuid.UUID, period controller.DatePeriodDTO)) *MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(controller.DatePeriodDTO))
	})
	return _c
}

func (_c *MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call) Return(_a0 bool, _a1 error) *MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, controller.DatePeriodDTO) (bool, error)) *MockVehicleRepository_VehicleHasBookedDatesOnPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVehicleRepository creates a new instance of MockVehicleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVehicleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVehicleRepository {
	mock := &MockVehicleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
