// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	controller "github.com/iondodon/go-vbs/booking/controller"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVehicleAvailabilityService is an autogenerated mock type for the VehicleAvailabilityService type
type MockVehicleAvailabilityService struct {
	mock.Mock
}

type MockVehicleAvailabilityService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVehicleAvailabilityService) EXPECT() *MockVehicleAvailabilityService_Expecter {
	return &MockVehicleAvailabilityService_Expecter{mock: &_m.Mock}
}

// CheckForPeriod provides a mock function with given fields: ctx, vUUID, period
func (_m *MockVehicleAvailabilityService) CheckForPeriod(ctx context.Context, vUUID uuid.UUID, period controller.DatePeriodDTO) (bool, error) {
	ret := _m.Called(ctx, vUUID, period)

	if len(ret) == 0 {
		panic("no return value specified for CheckForPeriod")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, controller.DatePeriodDTO) (bool, error)); ok {
		return rf(ctx, vUUID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, controller.DatePeriodDTO) bool); ok {
		r0 = rf(ctx, vUUID, period)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, controller.DatePeriodDTO) error); ok {
		r1 = rf(ctx, vUUID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVehicleAvailabilityService_CheckForPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckForPeriod'
type MockVehicleAvailabilityService_CheckForPeriod_Call struct {
	*mock.Call
}

// CheckForPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - vUUID uuid.UUID
//   - period controller.DatePeriodDTO
func (_e *MockVehicleAvailabilityService_Expecter) CheckForPeriod(ctx interface{}, vUUID interface{}, period interface{}) *MockVehicleAvailabilityService_CheckForPeriod_Call {
	return &MockVehicleAvailabilityService_CheckForPeriod_Call{Call: _e.mock.On("CheckForPeriod", ctx, vUUID, period)}
}

func (_c *MockVehicleAvailabilityService_CheckForPeriod_Call) Run(run func(ctx context.Context, vUUID uuid.UUID, period controller.DatePeriodDTO)) *MockVehicleAvailabilityService_CheckForPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(controller.DatePeriodDTO))
	})
	return _c
}

func (_c *MockVehicleAvailabilityService_CheckForPeriod_Call) Return(_a0 bool, _a1 error) *MockVehicleAvailabilityService_CheckForPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVehicleAvailabilityService_CheckForPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, controller.DatePeriodDTO) (bool, error)) *MockVehicleAvailabilityService_CheckForPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVehicleAvailabilityService creates a new instance of MockVehicleAvailabilityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVehicleAvailabilityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVehicleAvailabilityService {
	mock := &MockVehicleAvailabilityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
