// Code generated by gobok v1.0.0. DO NOT EDIT.

package bookingdate

import (
	bdRepoPkg "github.com/iondodon/go-vbs/repository/bookingdate"
)

func NewGetBookingDates(bdRepo bdRepoPkg.BookingDateRepository) getBookingDates {
	return getBookingDates{
		bdRepo: bdRepo,
	}
}
