// Code generated by gobok v1.0.0. DO NOT EDIT.

package bookingdate

import (
	bdRepoPkg "github.com/iondodon/go-vbs/repository/bookingdate"
)

type GetBookingDatesBuilder struct {
	instance *GetBookingDates
}

func NewGetBookingDatesBuilder() *GetBookingDatesBuilder {
	return &GetBookingDatesBuilder{
		instance: &GetBookingDates{},
	}
}

func (b *GetBookingDatesBuilder) BdRepo(v bdRepoPkg.BookingDateRepository) *GetBookingDatesBuilder {
	b.instance.bdRepo = v
	return b
}

func (b *GetBookingDatesBuilder) Build() *GetBookingDates {
	return b.instance
}
