// Code generated by gobok v1.0.0. DO NOT EDIT.

package vehicle

import (
	vehRepo "github.com/iondodon/go-vbs/repository/vehicle"
	vehRepoPkg "github.com/iondodon/go-vbs/repository/vehicle"
)

func NewGetVehicle(vehicleRepository vehRepo.VehicleRepository) getVehicle {
	return getVehicle{
		vehicleRepository: vehicleRepository,
	}
}

func NewIsAvailableForHire(vehRepo vehRepoPkg.VehicleRepository) isAvailableForHire {
	return isAvailableForHire{
		vehRepo: vehRepo,
	}
}
