// Code generated by gobok v1.0.0. DO NOT EDIT.

package customer

import (
	"github.com/iondodon/go-vbs/repository"
)

type CustomerRepositoryBuilder struct {
	instance *CustomerRepository
}

func NewCustomerRepositoryBuilder() *CustomerRepositoryBuilder {
	return &CustomerRepositoryBuilder{
		instance: &CustomerRepository{},
	}
}

func (b *CustomerRepositoryBuilder) Queries(v *repository.Queries) *CustomerRepositoryBuilder {
	b.instance.queries = v
	return b
}

func (b *CustomerRepositoryBuilder) Build() *CustomerRepository {
	return b.instance
}
