// Code generated by gobok v1.0.0. DO NOT EDIT.

package customer

import (
	"github.com/iondodon/go-vbs/repository"
)

func NewCustomerRepository(queries *repository.Queries) customerRepository {
	return customerRepository{
		queries: queries,
	}
}
