// Code generated by gobok v1.0.0. DO NOT EDIT.

package booking

import (
	bookingRepo "github.com/iondodon/go-vbs/repository/booking"
	bookingRepos "github.com/iondodon/go-vbs/repository/booking"
	custRepo "github.com/iondodon/go-vbs/repository/customer"
	vehRepo "github.com/iondodon/go-vbs/repository/vehicle"
	bdUCs "github.com/iondodon/go-vbs/usecase/bookingdate"
	vehUCs "github.com/iondodon/go-vbs/usecase/vehicle"
	"log"
)

func NewBookVehicle(infoLog *log.Logger, errorLog *log.Logger, vehRepo vehRepo.VehicleRepository, custRepo custRepo.CustomerRepository, bookingRepo bookingRepo.BookingRepository, isAvailableForHire vehUCs.IsAvailableForHire, getBookingDates bdUCs.GetBookingDates) BookVehicle {
	return BookVehicle{
		infoLog:            infoLog,
		errorLog:           errorLog,
		vehRepo:            vehRepo,
		custRepo:           custRepo,
		bookingRepo:        bookingRepo,
		isAvailableForHire: isAvailableForHire,
		getBookingDates:    getBookingDates,
	}
}

func NewGetAllBookings(bookingRepo bookingRepos.BookingRepository) GetAllBookings {
	return GetAllBookings{
		bookingRepo: bookingRepo,
	}
}
