// Code generated by gobok v1.0.0. DO NOT EDIT.

package vehicle

import (
	"github.com/iondodon/go-vbs/repository"
)

func NewVehicleRepository(queries *repository.Queries) VehicleRepository {
	return VehicleRepository{
		queries: queries,
	}
}
