// Code generated by gobok v1.0.0. DO NOT EDIT.

package vehicle

import (
	"github.com/iondodon/go-vbs/repository"
)

type VehicleRepositoryBuilder struct {
	instance *VehicleRepository
}

func NewVehicleRepositoryBuilder() *VehicleRepositoryBuilder {
	return &VehicleRepositoryBuilder{
		instance: &VehicleRepository{},
	}
}

func (b *VehicleRepositoryBuilder) Queries(v *repository.Queries) *VehicleRepositoryBuilder {
	b.instance.queries = v
	return b
}

func (b *VehicleRepositoryBuilder) Build() *VehicleRepository {
	return b.instance
}
