// Code generated by gobok v1.0.0. DO NOT EDIT.

package controller

import (
	"database/sql"
	bookingUCs "github.com/iondodon/go-vbs/usecase/booking"
	vehUCs "github.com/iondodon/go-vbs/usecase/vehicle"
	"log"
)

func NewBookingController(infoLog *log.Logger, errorLog *log.Logger, db *sql.DB, bookVehicleUseCase bookingUCs.BookVehicle, getAllBookings bookingUCs.GetAllBookings) bookingController {
	return bookingController{
		infoLog:            infoLog,
		errorLog:           errorLog,
		db:                 db,
		bookVehicleUseCase: bookVehicleUseCase,
		getAllBookings:     getAllBookings,
	}
}

func NewTokenController(infoLog *log.Logger, errorLog *log.Logger) tokenController {
	return tokenController{
		infoLog:  infoLog,
		errorLog: errorLog,
	}
}

func NewVehicleController(infoLog *log.Logger, errorLog *log.Logger, getVehicleUseCase vehUCs.GetVehicle) vehicleController {
	return vehicleController{
		infoLog:           infoLog,
		errorLog:          errorLog,
		getVehicleUseCase: getVehicleUseCase,
	}
}
