// Code generated by gobok v1.0.0. DO NOT EDIT.

package controller

import (
	"database/sql"
	bookingUCs "github.com/iondodon/go-vbs/usecase/booking"
	"log"
)

type bookingControllerBuilder struct {
	instance bookingController
}

func NewbookingControllerBuilder() *bookingControllerBuilder {
	return &bookingControllerBuilder{
		instance: bookingController{},
	}
}

func (b *bookingControllerBuilder) SetinfoLog(v *log.Logger) *bookingControllerBuilder {
	b.instance.infoLog = v
	return b
}
func (b *bookingControllerBuilder) SeterrorLog(v *log.Logger) *bookingControllerBuilder {
	b.instance.errorLog = v
	return b
}
func (b *bookingControllerBuilder) Setdb(v *sql.DB) *bookingControllerBuilder {
	b.instance.db = v
	return b
}
func (b *bookingControllerBuilder) SetbookVehicleUseCase(v bookingUCs.BookVehicle) *bookingControllerBuilder {
	b.instance.bookVehicleUseCase = v
	return b
}
func (b *bookingControllerBuilder) SetgetAllBookings(v bookingUCs.GetAllBookings) *bookingControllerBuilder {
	b.instance.getAllBookings = v
	return b
}

func (b *bookingControllerBuilder) Build() *bookingController {
	return &b.instance
}
